export const MAX_CERTIFICATE_BACKGROUND_BYTES = 10 * 1024 * 1024;
export const MAX_CERTIFICATE_SIGNATURE_BYTES = 2 * 1024 * 1024;
export const CERTIFICATE_BACKGROUND_WIDTH = 2376;
export const CERTIFICATE_BACKGROUND_HEIGHT = 1680;
export const CERTIFICATE_BACKGROUND_ASPECT_RATIO =
  CERTIFICATE_BACKGROUND_WIDTH / CERTIFICATE_BACKGROUND_HEIGHT;
export const CERTIFICATE_IMAGE_ACCEPT = ".jpeg,.jpg,.png,.webp";
